// client/sound.js - the noises, synthesised.
//
// No audio files. Every sound here is generated by an oscillator and an
// envelope, which is both what a 1988 machine did and what keeps the repo a
// repo rather than a media library. It also means a sound is a few numbers -
// pitch, shape, length - and can be tuned by reading rather than by listening
// to a file somebody exported once.
//
// Sound is driven by the VIEW's event list, which is already fog-filtered: you
// hear your own hulls firing and your own ship being hit, and you do not hear
// a battle over the horizon. The one deliberate exception is the missile-lock
// warning, which is not an event but a standing condition - and it is the whole
// reason to have sound at all, because a warning you can hear is a warning you
// can act on while you are busy flying.
//
// Browsers refuse to make noise before the user has interacted with the page,
// so the audio context is created on the first key or click and not before.

const VOICES = {
  // event code -> voice. Codes are engine/events.js.
  8: { freq: 320, to: 640, ms: 120, type: 'square', gain: 0.05 }, // unit launched
  9: { freq: 520, to: 300, ms: 140, type: 'square', gain: 0.05 }, // unit recovered
  10: { freq: 220, to: 60, ms: 420, type: 'sawtooth', gain: 0.09 }, // unit lost
  17: { freq: 440, to: 880, ms: 300, type: 'square', gain: 0.08 }, // island captured
  18: { freq: 660, to: 220, ms: 900, type: 'triangle', gain: 0.12 }, // war over
  20: { freq: 140, to: 90, ms: 180, type: 'sawtooth', gain: 0.10 }, // carrier damaged
  21: { freq: 120, to: 40, ms: 1200, type: 'sawtooth', gain: 0.14 }, // carrier sunk
  24: { freq: 380, to: 500, ms: 100, type: 'sine', gain: 0.04 }, // supply delivered
  26: { freq: 900, to: 260, ms: 70, type: 'square', gain: 0.03 }, // shot fired
  27: { freq: 200, to: 120, ms: 90, type: 'square', gain: 0.05 }, // unit hit
  31: { freq: 300, to: 600, ms: 200, type: 'sine', gain: 0.05 }, // island built
  32: { freq: 420, to: 700, ms: 220, type: 'square', gain: 0.06 }, // hull replaced
  34: { freq: 260, to: 80, ms: 340, type: 'sawtooth', gain: 0.08 }, // turret lost
  36: { freq: 500, to: 900, ms: 400, type: 'triangle', gain: 0.09 }, // island converted
  37: { freq: 1400, to: 300, ms: 260, type: 'sawtooth', gain: 0.07 }, // flares away
};

// The lock warning: two tones, over and over, at a pace that is hard to ignore
// and impossible to mistake for anything else in the mix.
const WARN_MS = 700;

function createSound() {
  return { ctx: undefined, muted: false, lastWarnMs: 0, lastShotMs: 0 };
}

// Made on the first gesture, because a browser will not allow it earlier.
function wakeSound(sound) {
  if (sound.ctx !== undefined) return sound.ctx;
  const Ctx = window.AudioContext || window.webkitAudioContext;
  if (Ctx === undefined) return undefined;
  sound.ctx = new Ctx();
  return sound.ctx;
}

// One voice: an oscillator sliding from one pitch to another under a decaying
// envelope. Everything in this file is this function with different numbers.
//
// `afterSeconds` schedules it on the AUDIO clock rather than a timer. That is
// sample-accurate where setTimeout is not, and it keeps this module free of the
// DOM entirely - which is why it can be tested without a browser.
function tone(sound, voice, afterSeconds) {
  const ctx = sound.ctx;
  if (ctx === undefined || sound.muted) return;
  const now = ctx.currentTime + (afterSeconds === undefined ? 0 : afterSeconds);
  const seconds = voice.ms / 1000;
  const osc = ctx.createOscillator();
  const gain = ctx.createGain();
  osc.type = voice.type;
  osc.frequency.setValueAtTime(voice.freq, now);
  osc.frequency.exponentialRampToValueAtTime(Math.max(20, voice.to), now + seconds);
  gain.gain.setValueAtTime(voice.gain, now);
  gain.gain.exponentialRampToValueAtTime(0.0001, now + seconds);
  osc.connect(gain);
  gain.connect(ctx.destination);
  osc.start(now);
  osc.stop(now + seconds + 0.02);
}

// Gunfire is the one event that can arrive dozens of times a second, and a
// hundred overlapping clicks is noise rather than sound. One per interval.
function throttled(sound, nowMs, key, everyMs) {
  if (nowMs - sound[key] < everyMs) return false;
  sound[key] = nowMs;
  return true;
}

// Everything that happened this snapshot, as sound. The view's event list is
// already filtered to what this seat is entitled to know.
function playEvents(sound, events, nowMs) {
  if (sound.ctx === undefined || sound.muted) return;
  for (const event of events) {
    const voice = VOICES[event.code];
    if (voice === undefined) continue;
    if (event.code === 26 && !throttled(sound, nowMs, 'lastShotMs', 90)) continue;
    tone(sound, voice);
  }
}

// The standing warning: a guided round is in the air with this ship's name on
// it. Repeats while that is true, and stops the moment it is not.
function playWarning(sound, view, nowMs) {
  if (sound.ctx === undefined || sound.muted) return false;
  let locked = false;
  for (const shot of view.shots) {
    if (shot.warn === 1) locked = true;
  }
  if (!locked) return false;
  if (!throttled(sound, nowMs, 'lastWarnMs', WARN_MS)) return true;
  tone(sound, { freq: 1180, to: 1180, ms: 130, type: 'square', gain: 0.09 });
  tone(sound, { freq: 880, to: 880, ms: 130, type: 'square', gain: 0.09 }, 0.17);
  return true;
}

function toggleMute(sound) {
  sound.muted = !sound.muted;
  return sound.muted;
}

// The menu ambience (owner ruling 2026-08-23): distant surf and distant
// guns under the diorama. Surf is looped noise through a lowpass with a slow
// swell riding the gain; the guns are the same tone() thumps the war uses,
// pitched low and far between. Synthesised like everything else - the menu
// is not the place the repo becomes a media library.
function startAmbience(sound) {
  const ctx = sound.ctx;
  if (ctx === undefined || sound.muted) return undefined;

  const buffer = ctx.createBuffer(1, ctx.sampleRate * 2, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1;
  const surf = ctx.createBufferSource();
  surf.buffer = buffer;
  surf.loop = true;
  const wash = ctx.createBiquadFilter();
  wash.type = 'lowpass';
  wash.frequency.value = 420;
  wash.Q.value = 0.6;
  const surfGain = ctx.createGain();
  surfGain.gain.value = 0.045;
  const swell = ctx.createOscillator();
  swell.type = 'sine';
  swell.frequency.value = 0.11;
  const swellDepth = ctx.createGain();
  swellDepth.gain.value = 0.025;
  swell.connect(swellDepth);
  swellDepth.connect(surfGain.gain);
  surf.connect(wash);
  wash.connect(surfGain);
  surfGain.connect(ctx.destination);
  surf.start();
  swell.start();

  let timer = 0;
  const salvo = () => {
    tone(sound, { freq: 72, to: 36, ms: 900, type: 'sine', gain: 0.06 });
    tone(sound, { freq: 190, to: 60, ms: 260, type: 'triangle', gain: 0.025 });
    // Sometimes an answer from the other side of the island.
    if (Math.random() < 0.4) {
      tone(sound, { freq: 60, to: 32, ms: 800, type: 'sine', gain: 0.045 }, 0.6);
    }
    timer = setTimeout(salvo, 6000 + Math.random() * 9000);
  };
  timer = setTimeout(salvo, 2500);

  return {
    stop: () => {
      clearTimeout(timer);
      surf.stop();
      swell.stop();
      surfGain.disconnect();
    },
  };
}

export { VOICES, createSound, wakeSound, tone, playEvents, playWarning, toggleMute, startAmbience };
