// tools/gen_trig.mjs - regenerates shared/trig_table.js.
//
// The engine may not call Math.sin at runtime: floats are not portable and not
// reproducible. Instead the tables below are generated once, committed, and
// read as plain integers. Run `npm run trig` after changing a table size, then
// re-pin the golden hashes (any change here moves every trajectory).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'shared', 'trig_table.js');

const ANGLE_FULL = 65536;
const ANGLE_QUARTER = 16384;
const SIN_ONE = 65536; // sin table scale: 65536 == 1.0
const SIN_STEP = 16; // BAM per table entry
const SIN_ENTRIES = ANGLE_QUARTER / SIN_STEP + 1; // 1025, inclusive of pi/2

const ATAN_STEPS = 4096; // ratio 0..1 mapped onto 0..4096
const ATAN_STRIDE = 16; // entries every 16 ratio steps
const ATAN_ENTRIES = ATAN_STEPS / ATAN_STRIDE + 1; // 257, inclusive of 1.0

function buildSinTable() {
  const values = [];
  for (let i = 0; i < SIN_ENTRIES; i++) {
    const bam = i * SIN_STEP;
    const radians = (bam / ANGLE_FULL) * Math.PI * 2;
    values.push(Math.round(Math.sin(radians) * SIN_ONE));
  }
  return values;
}

function buildAtanTable() {
  const values = [];
  for (let i = 0; i < ATAN_ENTRIES; i++) {
    const ratio = (i * ATAN_STRIDE) / ATAN_STEPS;
    const radians = Math.atan(ratio);
    values.push(Math.round((radians / (Math.PI * 2)) * ANGLE_FULL));
  }
  return values;
}

function formatTable(name, values, perLine) {
  const lines = [];
  for (let i = 0; i < values.length; i += perLine) {
    lines.push('  ' + values.slice(i, i + perLine).join(', ') + ',');
  }
  return `const ${name} = [\n${lines.join('\n')}\n];\n`;
}

const header = `// shared/trig_table.js - GENERATED by tools/gen_trig.mjs. Do not edit by hand.
//
// SIN_TABLE[i] = round(sin(i * ${SIN_STEP} BAM) * ${SIN_ONE}), i in [0, ${SIN_ENTRIES - 1}] covering
// one quadrant inclusive. ATAN_TABLE[i] = round(atan(i * ${ATAN_STRIDE} / ${ATAN_STEPS}) in BAM),
// covering ratios 0..1 inclusive.

`;

const body = [
  `const SIN_ONE = ${SIN_ONE};`,
  `const SIN_STEP = ${SIN_STEP};`,
  `const ATAN_STEPS = ${ATAN_STEPS};`,
  `const ATAN_STRIDE = ${ATAN_STRIDE};`,
  '',
  formatTable('SIN_TABLE', buildSinTable(), 12),
  formatTable('ATAN_TABLE', buildAtanTable(), 12),
  'export { SIN_ONE, SIN_STEP, ATAN_STEPS, ATAN_STRIDE, SIN_TABLE, ATAN_TABLE };',
  '',
].join('\n');

writeFileSync(OUT, header + body);
process.stdout.write(`wrote ${OUT}\n`);
